-- P2P Deal schema synchronizer (PostgreSQL 18)
-- Creates missing tables and adds missing columns, constraints, sequences, and indexes.
-- Safe to run repeatedly on an existing database.
-- IMPORTANT: transactions_history is intentionally limited to Completed deals only.

BEGIN;

CREATE SCHEMA IF NOT EXISTS public;

-- Sequences
CREATE SEQUENCE IF NOT EXISTS public.user_login_user_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.admin_login_admin_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.user_wallet_wallet_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.room_room_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.room_messages_message_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.transactions_history_transaction_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.deal_proofs_proof_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.disputes_dispute_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.dispute_resolution_resolution_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.faq_questions_question_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.room_reminders_reminder_id_seq AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- Core authentication tables
CREATE TABLE IF NOT EXISTS public.user_login (
    user_id integer NOT NULL DEFAULT nextval('public.user_login_user_id_seq'::regclass),
    email character varying(255) NOT NULL,
    passwordhash character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.admin_login (
    admin_id integer NOT NULL DEFAULT nextval('public.admin_login_admin_id_seq'::regclass),
    email character varying(255) NOT NULL,
    passwordhash character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.announcements (
    announcement_id integer
        GENERATED BY DEFAULT AS IDENTITY,
    title character varying(255) NOT NULL,
    message text NOT NULL,
    created_by integer,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone
        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT announcements_pkey
        PRIMARY KEY (announcement_id),

    CONSTRAINT announcements_title_not_blank
        CHECK (length(trim(title)) > 0),

    CONSTRAINT announcements_message_not_blank
        CHECK (length(trim(message)) > 0)
);

CREATE INDEX IF NOT EXISTS
    announcements_active_created_idx
ON public.announcements (
    is_active,
    created_at DESC
);

CREATE TABLE IF NOT EXISTS public.user_details (
    user_id integer NOT NULL,
    firstname character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL,
    phonenumber character varying(20) NOT NULL,
    nationalidentity_id character varying(30) NOT NULL,
    dob date NOT NULL,
    address text NOT NULL,
    verify_status character varying(20) NOT NULL,
    national_id_front character varying(255),
    national_id_back character varying(255),
    profile_picture character varying(255),
    reject_reason text,
    reject_comment text,
    reviewed_at timestamp without time zone,
    reviewed_by integer,
    bio character varying(120),
    show_email boolean DEFAULT false,
    show_phone boolean DEFAULT false,
    profile_visibility character varying(20) DEFAULT 'public'::character varying,
    username character varying(30),
    display_name character varying(50),
    joined_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_profile_visibility CHECK (profile_visibility::text = ANY (ARRAY['public','partners','private']::text[])),
    CONSTRAINT chk_username_format CHECK (username IS NULL OR username::text ~ '^[a-z0-9_]{3,30}$'::text),
    CONSTRAINT chk_username_length CHECK (username IS NULL OR (length(username::text) >= 3 AND length(username::text) <= 30)),
    CONSTRAINT user_details_verify_status_check CHECK (verify_status::text = ANY (ARRAY['Pending','Verified','Rejected']::text[]))
);

CREATE TABLE IF NOT EXISTS public.user_wallet (
    wallet_id integer NOT NULL DEFAULT nextval('public.user_wallet_wallet_id_seq'::regclass),
    user_id integer NOT NULL,
    available_balance numeric(12,2) DEFAULT 0.00 NOT NULL,
    pending_balance numeric(12,2) DEFAULT 0.00 NOT NULL,
    total_received numeric(12,2) DEFAULT 0.00 NOT NULL,
    total_withdrawn numeric(12,2) DEFAULT 0.00 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Deal tables
CREATE TABLE IF NOT EXISTS public.room (
    room_id integer NOT NULL DEFAULT nextval('public.room_room_id_seq'::regclass),
    room_code character varying(10) NOT NULL,
    created_by integer NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    archived_until timestamp without time zone,
    item_name character varying(255),
    item_description text,
    agreed_price numeric(12,2),
    payment_status character varying(20) DEFAULT 'Waiting'::character varying,
    bakong_transaction_id character varying(100),
    payment_verified_at timestamp without time zone,
    payment_provider character varying(30) DEFAULT 'Bakong'::character varying,
    invited_user_id integer,
    escrow_fee numeric(10,2) DEFAULT 0,
    total_paid numeric(10,2) DEFAULT 0,
    shipping_status character varying(30) DEFAULT 'NotShipped'::character varying,
    courier_name character varying(100),
    tracking_number character varying(100),
    cancel_requested_by integer,
    cancel_reason text,
    completed_at timestamp without time zone,
    reinvite_count integer DEFAULT 0 NOT NULL,
    max_reinvites integer DEFAULT 3 NOT NULL,
    product_type character varying(20) DEFAULT 'Physical'::character varying,
    current_step character varying(30) DEFAULT 'RoleSelection'::character varying,
CONSTRAINT room_current_step_check CHECK (
    current_step::text = ANY (
        ARRAY[
            'RoleSelection',
            'DealConfirmation',
            'FeeConfirmation',
            'Payment',
            'Delivery',
            'Completed',
            'Cancelled'
        ]::text[]
    )
),
CONSTRAINT room_payment_status_check CHECK (
    payment_status::text = ANY (ARRAY['Waiting','Paid','Released','Refunded']::text[])),
    CONSTRAINT room_product_type_check CHECK (product_type::text = ANY (ARRAY['Physical','Digital']::text[])),
    CONSTRAINT room_status_check CHECK (status::text = ANY (ARRAY['Waiting','Accepted','Rejected','RolesAssigned','Completed','Cancelled']::text[]))
);

CREATE TABLE IF NOT EXISTS public.buyer (
    room_id integer NOT NULL,
    buyer_id integer NOT NULL,
    agreed_amount numeric(12,2),
    ready boolean DEFAULT false NOT NULL,
    joined_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    amount_confirmed boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS public.seller (
    room_id integer NOT NULL,
    seller_id integer NOT NULL,
    agreed_amount numeric(12,2),
    ready boolean DEFAULT false NOT NULL,
    joined_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    amount_confirmed boolean DEFAULT false NOT NULL
);
CREATE TABLE IF NOT EXISTS public.deal_fee_agreement (
    room_id integer NOT NULL,
    fee_payer character varying(6),
    proposed_by integer,
    fee_amount numeric(12,2) NOT NULL,
    buyer_deposit numeric(12,2),
    seller_receive numeric(12,2),
    buyer_confirmed boolean DEFAULT false NOT NULL,
    seller_confirmed boolean DEFAULT false NOT NULL,
    updated_at timestamp without time zone
        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT deal_fee_agreement_pkey
        PRIMARY KEY (room_id),
    CONSTRAINT deal_fee_payer_check
        CHECK (
            fee_payer IS NULL
            OR fee_payer::text = ANY (
                ARRAY['buyer', 'seller']::text[]
            )
        )
);
CREATE TABLE IF NOT EXISTS public.deal_payment_attempt (
    payment_attempt_id integer
        GENERATED BY DEFAULT AS IDENTITY,
    room_id integer NOT NULL,
    khqr_md5 character varying(100) NOT NULL,
    qr_payload text NOT NULL,
    expected_amount numeric(12,2) NOT NULL,
    currency character varying(3)
        DEFAULT 'USD'::character varying NOT NULL,
    receiver_account character varying(255) NOT NULL,
    status character varying(20)
        DEFAULT 'Generated'::character varying NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    verification_attempts integer DEFAULT 0 NOT NULL,
    last_verification_at timestamp with time zone,
    verified_at timestamp with time zone,
    created_at timestamp with time zone
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT deal_payment_attempt_pkey
        PRIMARY KEY (payment_attempt_id),

    CONSTRAINT deal_payment_attempt_room_fkey
        FOREIGN KEY (room_id)
        REFERENCES public.room(room_id)
        ON DELETE CASCADE,

    CONSTRAINT deal_payment_attempt_md5_unique
        UNIQUE (khqr_md5),

    CONSTRAINT deal_payment_attempt_amount_positive
        CHECK (expected_amount > 0),

    CONSTRAINT deal_payment_attempt_attempts_nonnegative
        CHECK (verification_attempts >= 0),

    CONSTRAINT deal_payment_attempt_currency_check
    CHECK (currency = 'USD'),

    CONSTRAINT deal_payment_attempt_status_check
        CHECK (
            status::text = ANY (
                ARRAY[
                    'Generated',
                    'Verified',
                    'Expired',
                    'Failed'
                ]::text[]
            )
        )
);
CREATE TABLE IF NOT EXISTS public.room_messages (
    message_id integer NOT NULL DEFAULT nextval('public.room_messages_message_id_seq'::regclass),
    room_id integer NOT NULL,
    sender_id integer NOT NULL,
    message text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.deal_proofs (
    proof_id integer NOT NULL DEFAULT nextval('public.deal_proofs_proof_id_seq'::regclass),
    room_id integer NOT NULL,
    user_id integer NOT NULL,
    proof_type character varying(30) NOT NULL,
    file_path character varying(255) NOT NULL,
    uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    description text,
    courier_name character varying(100),
    tracking_number character varying(100),
    reviewed boolean DEFAULT false,
    admin_note text,
    CONSTRAINT deal_proofs_type_check CHECK (proof_type::text = 'Fulfillment'::text)
);

CREATE TABLE IF NOT EXISTS public.transactions_history (
    transaction_id integer NOT NULL DEFAULT nextval('public.transactions_history_transaction_id_seq'::regclass),
    room_id integer,
    room_code character varying(10),
    buyer_id integer NOT NULL,
    seller_id integer NOT NULL,
    item_name character varying(255),
    item_description text,
    agreed_price numeric(12,2),
    transaction_amount numeric(12,2) NOT NULL,
    fee_amount numeric(12,2) NOT NULL,
    seller_receive numeric(12,2) NOT NULL,
    platform_income numeric(12,2) NOT NULL,
    fulfillment_proof character varying(255),
    fulfillment_uploaded_at timestamp without time zone,
    payment_verified_at timestamp without time zone,
    released_at timestamp without time zone,
    transaction_status character varying(20) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp without time zone,
    bakong_transaction_id character varying(100),
    payment_provider character varying(30) DEFAULT 'Bakong'::character varying,
    fee_payer character varying(6),
    CONSTRAINT transactions_history_status_check
CHECK (
    transaction_status::text = ANY (
        ARRAY['Completed']::text[]
    )
)
);

-- Dispute and support tables
CREATE TABLE IF NOT EXISTS public.disputes (
    dispute_id integer NOT NULL DEFAULT nextval('public.disputes_dispute_id_seq'::regclass),
    room_id integer NOT NULL,
    opened_by integer NOT NULL,
    against_user integer NOT NULL,
    dispute_type character varying(50) NOT NULL,
    buyer_choice character varying(30),
    status character varying(30) DEFAULT 'Open'::character varying,
    reason text,
    created_at timestamp without time zone DEFAULT now(),
    closed_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.dispute_resolution (
    resolution_id integer NOT NULL DEFAULT nextval('public.dispute_resolution_resolution_id_seq'::regclass),
    dispute_id integer NOT NULL,
    resolved_by integer NOT NULL,
    decision character varying(50) NOT NULL,
    refund_amount numeric(10,2) DEFAULT 0.00,
    winner_user integer,
    resolution_note text,
    resolved_at timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.faq_questions (
    question_id integer NOT NULL DEFAULT nextval('public.faq_questions_question_id_seq'::regclass),
    user_id integer NOT NULL,
    question text NOT NULL,
    status character varying(20) DEFAULT 'Pending'::character varying,
    admin_reply text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    answered_at timestamp without time zone,
    answered_by integer
);

CREATE TABLE IF NOT EXISTS public.room_reminders (
    reminder_id integer NOT NULL DEFAULT nextval('public.room_reminders_reminder_id_seq'::regclass),
    room_id integer NOT NULL,
    sender_id integer NOT NULL,
    receiver_id integer NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone,
    created_at timestamp without time zone
    CONSTRAINT chk_room_reminders_different_users CHECK (sender_id <> receiver_id)
);
ALTER TABLE public.user_notifications
    ADD COLUMN IF NOT EXISTS
        deleted_at timestamp without time zone;

-- Sequence ownership
ALTER SEQUENCE public.user_login_user_id_seq OWNED BY public.user_login.user_id;
ALTER SEQUENCE public.admin_login_admin_id_seq OWNED BY public.admin_login.admin_id;
ALTER SEQUENCE public.user_wallet_wallet_id_seq OWNED BY public.user_wallet.wallet_id;
ALTER SEQUENCE public.room_room_id_seq OWNED BY public.room.room_id;
ALTER SEQUENCE public.room_messages_message_id_seq OWNED BY public.room_messages.message_id;
ALTER SEQUENCE public.transactions_history_transaction_id_seq OWNED BY public.transactions_history.transaction_id;
ALTER SEQUENCE public.deal_proofs_proof_id_seq OWNED BY public.deal_proofs.proof_id;
ALTER SEQUENCE public.disputes_dispute_id_seq OWNED BY public.disputes.dispute_id;
ALTER SEQUENCE public.dispute_resolution_resolution_id_seq OWNED BY public.dispute_resolution.resolution_id;
ALTER SEQUENCE public.faq_questions_question_id_seq OWNED BY public.faq_questions.question_id;
ALTER SEQUENCE public.room_reminders_reminder_id_seq OWNED BY public.room_reminders.reminder_id;


-- Add any columns missing from an older/partial version of the schema.
ALTER TABLE public.user_login ADD COLUMN IF NOT EXISTS user_id integer NOT NULL DEFAULT nextval('public.user_login_user_id_seq'::regclass);
ALTER TABLE public.user_login ADD COLUMN IF NOT EXISTS email character varying(255) NOT NULL;
ALTER TABLE public.user_login ADD COLUMN IF NOT EXISTS passwordhash character varying(255) NOT NULL;
ALTER TABLE public.user_login ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.admin_login ADD COLUMN IF NOT EXISTS admin_id integer NOT NULL DEFAULT nextval('public.admin_login_admin_id_seq'::regclass);
ALTER TABLE public.admin_login ADD COLUMN IF NOT EXISTS email character varying(255) NOT NULL;
ALTER TABLE public.admin_login ADD COLUMN IF NOT EXISTS passwordhash character varying(255) NOT NULL;
ALTER TABLE public.admin_login ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS user_id integer NOT NULL;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS firstname character varying(50) NOT NULL;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS lastname character varying(50) NOT NULL;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS phonenumber character varying(20) NOT NULL;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS nationalidentity_id character varying(30) NOT NULL;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS dob date NOT NULL;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS address text NOT NULL;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS verify_status character varying(20) NOT NULL;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS national_id_front character varying(255);
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS national_id_back character varying(255);
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS profile_picture character varying(255);
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS reject_reason text;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS reject_comment text;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS reviewed_at timestamp without time zone;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS reviewed_by integer;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS bio character varying(120);
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS show_email boolean DEFAULT false;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS show_phone boolean DEFAULT false;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS profile_visibility character varying(20) DEFAULT 'public'::character varying;
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS username character varying(30);
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS display_name character varying(50);
ALTER TABLE public.user_details ADD COLUMN IF NOT EXISTS joined_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.user_wallet ADD COLUMN IF NOT EXISTS wallet_id integer NOT NULL DEFAULT nextval('public.user_wallet_wallet_id_seq'::regclass);
ALTER TABLE public.user_wallet ADD COLUMN IF NOT EXISTS user_id integer NOT NULL;
ALTER TABLE public.user_wallet ADD COLUMN IF NOT EXISTS available_balance numeric(12,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE public.user_wallet ADD COLUMN IF NOT EXISTS pending_balance numeric(12,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE public.user_wallet ADD COLUMN IF NOT EXISTS total_received numeric(12,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE public.user_wallet ADD COLUMN IF NOT EXISTS total_withdrawn numeric(12,2) DEFAULT 0.00 NOT NULL;
ALTER TABLE public.user_wallet ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.user_wallet ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS room_id integer NOT NULL DEFAULT nextval('public.room_room_id_seq'::regclass);
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS room_code character varying(10) NOT NULL;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS created_by integer NOT NULL;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS status character varying(20) NOT NULL;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS archived_until timestamp without time zone;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS item_name character varying(255);
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS item_description text;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS agreed_price numeric(12,2);
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS payment_status character varying(20) DEFAULT 'Waiting'::character varying;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS bakong_transaction_id character varying(100);
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS payment_verified_at timestamp without time zone;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS payment_provider character varying(30) DEFAULT 'Bakong'::character varying;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS invited_user_id integer;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS escrow_fee numeric(10,2) DEFAULT 0;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS total_paid numeric(10,2) DEFAULT 0;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS shipping_status character varying(30) DEFAULT 'NotShipped'::character varying;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS courier_name character varying(100);
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS tracking_number character varying(100);
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS cancel_requested_by integer;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS cancel_reason text;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS completed_at timestamp without time zone;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS reinvite_count integer DEFAULT 0 NOT NULL;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS max_reinvites integer DEFAULT 3 NOT NULL;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS product_type character varying(20) DEFAULT 'Physical'::character varying;
ALTER TABLE public.room ADD COLUMN IF NOT EXISTS current_step character varying(30) DEFAULT 'RoleSelection'::character varying;
ALTER TABLE public.buyer ADD COLUMN IF NOT EXISTS room_id integer NOT NULL;
ALTER TABLE public.buyer ADD COLUMN IF NOT EXISTS buyer_id integer NOT NULL;
ALTER TABLE public.buyer ADD COLUMN IF NOT EXISTS agreed_amount numeric(12,2);
ALTER TABLE public.buyer ADD COLUMN IF NOT EXISTS ready boolean DEFAULT false NOT NULL;
ALTER TABLE public.buyer ADD COLUMN IF NOT EXISTS joined_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.buyer ADD COLUMN IF NOT EXISTS amount_confirmed boolean DEFAULT false NOT NULL;
ALTER TABLE public.seller ADD COLUMN IF NOT EXISTS room_id integer NOT NULL;
ALTER TABLE public.seller ADD COLUMN IF NOT EXISTS seller_id integer NOT NULL;
ALTER TABLE public.seller ADD COLUMN IF NOT EXISTS agreed_amount numeric(12,2);
ALTER TABLE public.seller ADD COLUMN IF NOT EXISTS ready boolean DEFAULT false NOT NULL;
ALTER TABLE public.seller ADD COLUMN IF NOT EXISTS joined_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.seller ADD COLUMN IF NOT EXISTS amount_confirmed boolean DEFAULT false NOT NULL;
ALTER TABLE public.deal_fee_agreement
    ADD COLUMN IF NOT EXISTS room_id integer;

ALTER TABLE public.deal_fee_agreement
    ADD COLUMN IF NOT EXISTS fee_payer character varying(6);

ALTER TABLE public.deal_fee_agreement
    ADD COLUMN IF NOT EXISTS proposed_by integer;

ALTER TABLE public.deal_fee_agreement
    ADD COLUMN IF NOT EXISTS fee_amount numeric(12,2);

ALTER TABLE public.deal_fee_agreement
    ADD COLUMN IF NOT EXISTS buyer_deposit numeric(12,2);

ALTER TABLE public.deal_fee_agreement
    ADD COLUMN IF NOT EXISTS seller_receive numeric(12,2);

ALTER TABLE public.deal_fee_agreement
    ADD COLUMN IF NOT EXISTS buyer_confirmed boolean
        DEFAULT false NOT NULL;

ALTER TABLE public.deal_fee_agreement
    ADD COLUMN IF NOT EXISTS seller_confirmed boolean
        DEFAULT false NOT NULL;

ALTER TABLE public.deal_fee_agreement
    ADD COLUMN IF NOT EXISTS updated_at
        timestamp without time zone
        DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE public.room_messages ADD COLUMN IF NOT EXISTS message_id integer NOT NULL DEFAULT nextval('public.room_messages_message_id_seq'::regclass);
ALTER TABLE public.room_messages ADD COLUMN IF NOT EXISTS room_id integer NOT NULL;
ALTER TABLE public.room_messages ADD COLUMN IF NOT EXISTS sender_id integer NOT NULL;
ALTER TABLE public.room_messages ADD COLUMN IF NOT EXISTS message text NOT NULL;
ALTER TABLE public.room_messages ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.deal_proofs ADD COLUMN IF NOT EXISTS proof_id integer NOT NULL DEFAULT nextval('public.deal_proofs_proof_id_seq'::regclass);
ALTER TABLE public.deal_proofs ADD COLUMN IF NOT EXISTS room_id integer NOT NULL;
ALTER TABLE public.deal_proofs ADD COLUMN IF NOT EXISTS user_id integer NOT NULL;
ALTER TABLE public.deal_proofs ADD COLUMN IF NOT EXISTS proof_type character varying(30) NOT NULL;
ALTER TABLE public.deal_proofs ADD COLUMN IF NOT EXISTS file_path character varying(255) NOT NULL;
ALTER TABLE public.deal_proofs ADD COLUMN IF NOT EXISTS uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.deal_proofs ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.deal_proofs ADD COLUMN IF NOT EXISTS courier_name character varying(100);
ALTER TABLE public.deal_proofs ADD COLUMN IF NOT EXISTS tracking_number character varying(100);
ALTER TABLE public.deal_proofs ADD COLUMN IF NOT EXISTS reviewed boolean DEFAULT false;
ALTER TABLE public.deal_proofs ADD COLUMN IF NOT EXISTS admin_note text;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS transaction_id integer NOT NULL DEFAULT nextval('public.transactions_history_transaction_id_seq'::regclass);
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS room_id integer;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS room_code character varying(10);
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS buyer_id integer NOT NULL;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS seller_id integer NOT NULL;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS item_name character varying(255);
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS item_description text;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS agreed_price numeric(12,2);
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS transaction_amount numeric(12,2) NOT NULL;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS fee_amount numeric(12,2) NOT NULL;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS seller_receive numeric(12,2) NOT NULL;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS platform_income numeric(12,2) NOT NULL;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS fulfillment_proof character varying(255);
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS fulfillment_uploaded_at timestamp without time zone;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS payment_verified_at timestamp without time zone;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS released_at timestamp without time zone;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS transaction_status character varying(20) NOT NULL;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS completed_at timestamp without time zone;
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS bakong_transaction_id character varying(100);
ALTER TABLE public.transactions_history ADD COLUMN IF NOT EXISTS payment_provider character varying(30) DEFAULT 'Bakong'::character varying;
ALTER TABLE public.transactions_history
    ADD COLUMN IF NOT EXISTS fee_payer
        character varying(6);
ALTER TABLE public.disputes ADD COLUMN IF NOT EXISTS dispute_id integer NOT NULL DEFAULT nextval('public.disputes_dispute_id_seq'::regclass);
ALTER TABLE public.disputes ADD COLUMN IF NOT EXISTS room_id integer NOT NULL;
ALTER TABLE public.disputes ADD COLUMN IF NOT EXISTS opened_by integer NOT NULL;
ALTER TABLE public.disputes ADD COLUMN IF NOT EXISTS against_user integer NOT NULL;
ALTER TABLE public.disputes ADD COLUMN IF NOT EXISTS dispute_type character varying(50) NOT NULL;
ALTER TABLE public.disputes ADD COLUMN IF NOT EXISTS buyer_choice character varying(30);
ALTER TABLE public.disputes ADD COLUMN IF NOT EXISTS status character varying(30) DEFAULT 'Open'::character varying;
ALTER TABLE public.disputes ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE public.disputes ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now();
ALTER TABLE public.disputes ADD COLUMN IF NOT EXISTS closed_at timestamp without time zone;
ALTER TABLE public.dispute_resolution ADD COLUMN IF NOT EXISTS resolution_id integer NOT NULL DEFAULT nextval('public.dispute_resolution_resolution_id_seq'::regclass);
ALTER TABLE public.dispute_resolution ADD COLUMN IF NOT EXISTS dispute_id integer NOT NULL;
ALTER TABLE public.dispute_resolution ADD COLUMN IF NOT EXISTS resolved_by integer NOT NULL;
ALTER TABLE public.dispute_resolution ADD COLUMN IF NOT EXISTS decision character varying(50) NOT NULL;
ALTER TABLE public.dispute_resolution ADD COLUMN IF NOT EXISTS refund_amount numeric(10,2) DEFAULT 0.00;
ALTER TABLE public.dispute_resolution ADD COLUMN IF NOT EXISTS winner_user integer;
ALTER TABLE public.dispute_resolution ADD COLUMN IF NOT EXISTS resolution_note text;
ALTER TABLE public.dispute_resolution ADD COLUMN IF NOT EXISTS resolved_at timestamp without time zone DEFAULT now();
ALTER TABLE public.faq_questions ADD COLUMN IF NOT EXISTS question_id integer NOT NULL DEFAULT nextval('public.faq_questions_question_id_seq'::regclass);
ALTER TABLE public.faq_questions ADD COLUMN IF NOT EXISTS user_id integer NOT NULL;
ALTER TABLE public.faq_questions ADD COLUMN IF NOT EXISTS question text NOT NULL;
ALTER TABLE public.faq_questions ADD COLUMN IF NOT EXISTS status character varying(20) DEFAULT 'Pending'::character varying;
ALTER TABLE public.faq_questions ADD COLUMN IF NOT EXISTS admin_reply text;
ALTER TABLE public.faq_questions ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.faq_questions ADD COLUMN IF NOT EXISTS answered_at timestamp without time zone;
ALTER TABLE public.faq_questions ADD COLUMN IF NOT EXISTS answered_by integer;
ALTER TABLE public.room_reminders ADD COLUMN IF NOT EXISTS reminder_id integer NOT NULL DEFAULT nextval('public.room_reminders_reminder_id_seq'::regclass);
ALTER TABLE public.room_reminders ADD COLUMN IF NOT EXISTS room_id integer NOT NULL;
ALTER TABLE public.room_reminders ADD COLUMN IF NOT EXISTS sender_id integer NOT NULL;
ALTER TABLE public.room_reminders ADD COLUMN IF NOT EXISTS receiver_id integer NOT NULL;
ALTER TABLE public.room_reminders ADD COLUMN IF NOT EXISTS is_read boolean DEFAULT false NOT NULL;
ALTER TABLE public.room_reminders ADD COLUMN IF NOT EXISTS created_at timestamp without time zone DEFAULT now() NOT NULL;

-- Primary keys and unique constraints
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_login_pkey' AND conrelid='public.user_login'::regclass) THEN ALTER TABLE public.user_login ADD CONSTRAINT user_login_pkey PRIMARY KEY (user_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_login_email_key' AND conrelid='public.user_login'::regclass) THEN ALTER TABLE public.user_login ADD CONSTRAINT user_login_email_key UNIQUE (email); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='admin_login_pkey' AND conrelid='public.admin_login'::regclass) THEN ALTER TABLE public.admin_login ADD CONSTRAINT admin_login_pkey PRIMARY KEY (admin_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='admin_login_email_key' AND conrelid='public.admin_login'::regclass) THEN ALTER TABLE public.admin_login ADD CONSTRAINT admin_login_email_key UNIQUE (email); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_details_pkey' AND conrelid='public.user_details'::regclass) THEN ALTER TABLE public.user_details ADD CONSTRAINT user_details_pkey PRIMARY KEY (user_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_details_nationalidentity_id_key' AND conrelid='public.user_details'::regclass) THEN ALTER TABLE public.user_details ADD CONSTRAINT user_details_nationalidentity_id_key UNIQUE (nationalidentity_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_wallet_pkey' AND conrelid='public.user_wallet'::regclass) THEN ALTER TABLE public.user_wallet ADD CONSTRAINT user_wallet_pkey PRIMARY KEY (wallet_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_wallet_user_id_key' AND conrelid='public.user_wallet'::regclass) THEN ALTER TABLE public.user_wallet ADD CONSTRAINT user_wallet_user_id_key UNIQUE (user_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='room_pkey' AND conrelid='public.room'::regclass) THEN ALTER TABLE public.room ADD CONSTRAINT room_pkey PRIMARY KEY (room_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='room_room_code_key' AND conrelid='public.room'::regclass) THEN ALTER TABLE public.room ADD CONSTRAINT room_room_code_key UNIQUE (room_code); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='room_bakong_transaction_id_unique' AND conrelid='public.room'::regclass) THEN ALTER TABLE public.room ADD CONSTRAINT room_bakong_transaction_id_unique UNIQUE (bakong_transaction_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='buyer_pkey' AND conrelid='public.buyer'::regclass) THEN ALTER TABLE public.buyer ADD CONSTRAINT buyer_pkey PRIMARY KEY (room_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='seller_pkey' AND conrelid='public.seller'::regclass) THEN ALTER TABLE public.seller ADD CONSTRAINT seller_pkey PRIMARY KEY (room_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='room_messages_pkey' AND conrelid='public.room_messages'::regclass) THEN ALTER TABLE public.room_messages ADD CONSTRAINT room_messages_pkey PRIMARY KEY (message_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='deal_proofs_pkey' AND conrelid='public.deal_proofs'::regclass) THEN ALTER TABLE public.deal_proofs ADD CONSTRAINT deal_proofs_pkey PRIMARY KEY (proof_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='transactions_history_pkey' AND conrelid='public.transactions_history'::regclass) THEN ALTER TABLE public.transactions_history ADD CONSTRAINT transactions_history_pkey PRIMARY KEY (transaction_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='transactions_history_bakong_transaction_id_unique' AND conrelid='public.transactions_history'::regclass) THEN ALTER TABLE public.transactions_history ADD CONSTRAINT transactions_history_bakong_transaction_id_unique UNIQUE (bakong_transaction_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='disputes_pkey' AND conrelid='public.disputes'::regclass) THEN ALTER TABLE public.disputes ADD CONSTRAINT disputes_pkey PRIMARY KEY (dispute_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dispute_resolution_pkey' AND conrelid='public.dispute_resolution'::regclass) THEN ALTER TABLE public.dispute_resolution ADD CONSTRAINT dispute_resolution_pkey PRIMARY KEY (resolution_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='faq_questions_pkey' AND conrelid='public.faq_questions'::regclass) THEN ALTER TABLE public.faq_questions ADD CONSTRAINT faq_questions_pkey PRIMARY KEY (question_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='room_reminders_pkey' AND conrelid='public.room_reminders'::regclass) THEN ALTER TABLE public.room_reminders ADD CONSTRAINT room_reminders_pkey PRIMARY KEY (reminder_id); END IF; END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'deal_fee_agreement_pkey'
          AND conrelid =
              'public.deal_fee_agreement'::regclass
    ) THEN
        ALTER TABLE public.deal_fee_agreement
            ADD CONSTRAINT deal_fee_agreement_pkey
            PRIMARY KEY (room_id);
    END IF;
END
$$;
-- Foreign keys
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_userdetails_login' AND conrelid='public.user_details'::regclass) THEN ALTER TABLE public.user_details ADD CONSTRAINT fk_userdetails_login FOREIGN KEY (user_id) REFERENCES public.user_login(user_id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_user_details_reviewed_by' AND conrelid='public.user_details'::regclass) THEN ALTER TABLE public.user_details ADD CONSTRAINT fk_user_details_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES public.admin_login(admin_id) ON DELETE SET NULL; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='announcements_created_by_fkey' AND conrelid='public.announcements'::regclass) THEN ALTER TABLE public.announcements ADD CONSTRAINT announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.admin_login(admin_id) ON DELETE SET NULL; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='user_wallet_user_id_fkey' AND conrelid='public.user_wallet'::regclass) THEN ALTER TABLE public.user_wallet ADD CONSTRAINT user_wallet_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_login(user_id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_room_creator' AND conrelid='public.room'::regclass) THEN ALTER TABLE public.room ADD CONSTRAINT fk_room_creator FOREIGN KEY (created_by) REFERENCES public.user_details(user_id) ON DELETE RESTRICT; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='room_invited_user_id_fkey' AND conrelid='public.room'::regclass) THEN ALTER TABLE public.room ADD CONSTRAINT room_invited_user_id_fkey FOREIGN KEY (invited_user_id) REFERENCES public.user_details(user_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='room_cancel_requested_by_fkey' AND conrelid='public.room'::regclass) THEN ALTER TABLE public.room ADD CONSTRAINT room_cancel_requested_by_fkey FOREIGN KEY (cancel_requested_by) REFERENCES public.user_login(user_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_buyer_room' AND conrelid='public.buyer'::regclass) THEN ALTER TABLE public.buyer ADD CONSTRAINT fk_buyer_room FOREIGN KEY (room_id) REFERENCES public.room(room_id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_buyer_user' AND conrelid='public.buyer'::regclass) THEN ALTER TABLE public.buyer ADD CONSTRAINT fk_buyer_user FOREIGN KEY (buyer_id) REFERENCES public.user_details(user_id) ON DELETE RESTRICT; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_seller_room' AND conrelid='public.seller'::regclass) THEN ALTER TABLE public.seller ADD CONSTRAINT fk_seller_room FOREIGN KEY (room_id) REFERENCES public.room(room_id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_seller_user' AND conrelid='public.seller'::regclass) THEN ALTER TABLE public.seller ADD CONSTRAINT fk_seller_user FOREIGN KEY (seller_id) REFERENCES public.user_details(user_id) ON DELETE RESTRICT; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_room_message_room' AND conrelid='public.room_messages'::regclass) THEN ALTER TABLE public.room_messages ADD CONSTRAINT fk_room_message_room FOREIGN KEY (room_id) REFERENCES public.room(room_id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_room_message_sender' AND conrelid='public.room_messages'::regclass) THEN ALTER TABLE public.room_messages ADD CONSTRAINT fk_room_message_sender FOREIGN KEY (sender_id) REFERENCES public.user_details(user_id) ON DELETE RESTRICT; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_proof_room' AND conrelid='public.deal_proofs'::regclass) THEN ALTER TABLE public.deal_proofs ADD CONSTRAINT fk_proof_room FOREIGN KEY (room_id) REFERENCES public.room(room_id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_proof_user' AND conrelid='public.deal_proofs'::regclass) THEN ALTER TABLE public.deal_proofs ADD CONSTRAINT fk_proof_user FOREIGN KEY (user_id) REFERENCES public.user_details(user_id) ON DELETE RESTRICT; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_transaction_buyer' AND conrelid='public.transactions_history'::regclass) THEN ALTER TABLE public.transactions_history ADD CONSTRAINT fk_transaction_buyer FOREIGN KEY (buyer_id) REFERENCES public.user_details(user_id) ON DELETE RESTRICT; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_transaction_seller' AND conrelid='public.transactions_history'::regclass) THEN ALTER TABLE public.transactions_history ADD CONSTRAINT fk_transaction_seller FOREIGN KEY (seller_id) REFERENCES public.user_details(user_id) ON DELETE RESTRICT; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='disputes_room_id_fkey' AND conrelid='public.disputes'::regclass) THEN ALTER TABLE public.disputes ADD CONSTRAINT disputes_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.room(room_id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='disputes_opened_by_fkey' AND conrelid='public.disputes'::regclass) THEN ALTER TABLE public.disputes ADD CONSTRAINT disputes_opened_by_fkey FOREIGN KEY (opened_by) REFERENCES public.user_login(user_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='disputes_against_user_fkey' AND conrelid='public.disputes'::regclass) THEN ALTER TABLE public.disputes ADD CONSTRAINT disputes_against_user_fkey FOREIGN KEY (against_user) REFERENCES public.user_login(user_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dispute_resolution_dispute_id_fkey' AND conrelid='public.dispute_resolution'::regclass) THEN ALTER TABLE public.dispute_resolution ADD CONSTRAINT dispute_resolution_dispute_id_fkey FOREIGN KEY (dispute_id) REFERENCES public.disputes(dispute_id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dispute_resolution_resolved_by_fkey' AND conrelid='public.dispute_resolution'::regclass) THEN ALTER TABLE public.dispute_resolution ADD CONSTRAINT dispute_resolution_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.admin_login(admin_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='dispute_resolution_winner_user_fkey' AND conrelid='public.dispute_resolution'::regclass) THEN ALTER TABLE public.dispute_resolution ADD CONSTRAINT dispute_resolution_winner_user_fkey FOREIGN KEY (winner_user) REFERENCES public.user_login(user_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='faq_questions_user_id_fkey' AND conrelid='public.faq_questions'::regclass) THEN ALTER TABLE public.faq_questions ADD CONSTRAINT faq_questions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_login(user_id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='faq_questions_answered_by_fkey' AND conrelid='public.faq_questions'::regclass) THEN ALTER TABLE public.faq_questions ADD CONSTRAINT faq_questions_answered_by_fkey FOREIGN KEY (answered_by) REFERENCES public.admin_login(admin_id); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_room_reminders_room' AND conrelid='public.room_reminders'::regclass) THEN ALTER TABLE public.room_reminders ADD CONSTRAINT fk_room_reminders_room FOREIGN KEY (room_id) REFERENCES public.room(room_id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_room_reminders_sender' AND conrelid='public.room_reminders'::regclass) THEN ALTER TABLE public.room_reminders ADD CONSTRAINT fk_room_reminders_sender FOREIGN KEY (sender_id) REFERENCES public.user_login(user_id) ON DELETE CASCADE; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='fk_room_reminders_receiver' AND conrelid='public.room_reminders'::regclass) THEN ALTER TABLE public.room_reminders ADD CONSTRAINT fk_room_reminders_receiver FOREIGN KEY (receiver_id) REFERENCES public.user_login(user_id) ON DELETE CASCADE; END IF; END $$;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'deal_fee_room_fkey'
          AND conrelid =
              'public.deal_fee_agreement'::regclass
    ) THEN
        ALTER TABLE public.deal_fee_agreement
            ADD CONSTRAINT deal_fee_room_fkey
            FOREIGN KEY (room_id)
            REFERENCES public.room(room_id)
            ON DELETE CASCADE;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'deal_fee_proposer_fkey'
          AND conrelid =
              'public.deal_fee_agreement'::regclass
    ) THEN
        ALTER TABLE public.deal_fee_agreement
            ADD CONSTRAINT deal_fee_proposer_fkey
            FOREIGN KEY (proposed_by)
            REFERENCES public.user_details(user_id)
            ON DELETE SET NULL;
    END IF;
END
$$;
-- Synchronize workflow and fee constraints without deleting data.
ALTER TABLE public.room
    DROP CONSTRAINT IF EXISTS room_current_step_check;

ALTER TABLE public.room
    ADD CONSTRAINT room_current_step_check
    CHECK (
        current_step::text = ANY (
            ARRAY[
                'RoleSelection',
                'DealConfirmation',
                'FeeConfirmation',
                'Payment',
                'Delivery',
                'Completed',
                'Cancelled'
            ]::text[]
        )
    );

ALTER TABLE public.deal_fee_agreement
    DROP CONSTRAINT IF EXISTS deal_fee_payer_check;

ALTER TABLE public.deal_fee_agreement
    ADD CONSTRAINT deal_fee_payer_check
    CHECK (
        fee_payer IS NULL
        OR fee_payer::text = ANY (
            ARRAY['buyer', 'seller']::text[]
        )
    );

ALTER TABLE public.transactions_history
    DROP CONSTRAINT IF EXISTS
        transactions_history_fee_payer_check;

ALTER TABLE public.transactions_history
    ADD CONSTRAINT transactions_history_fee_payer_check
    CHECK (
        fee_payer IS NULL
        OR fee_payer::text = ANY (
            ARRAY['buyer', 'seller']::text[]
        )
    );

ALTER TABLE public.transactions_history
    DROP CONSTRAINT IF EXISTS
        transactions_history_status_check;

ALTER TABLE public.transactions_history
    ADD CONSTRAINT transactions_history_status_check
    CHECK (
        transaction_status::text = 'Completed'::text
    );

-- ============================================================
-- Wallet and active deal escrow
-- ============================================================

-- Wallet totals must never become negative.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'user_wallet_balances_nonnegative'
          AND conrelid = 'public.user_wallet'::regclass
    ) THEN
        ALTER TABLE public.user_wallet
            ADD CONSTRAINT user_wallet_balances_nonnegative
            CHECK (
                available_balance >= 0
                AND pending_balance >= 0
                AND total_received >= 0
                AND total_withdrawn >= 0
            );
    END IF;
END
$$;


-- Temporary escrow state for an active deal.
CREATE TABLE IF NOT EXISTS public.deal_escrow (
    room_id integer NOT NULL,
    room_code character varying(10) NOT NULL,

    buyer_id integer NOT NULL,
    seller_id integer NOT NULL,

    payment_method character varying(10) NOT NULL,
    payment_attempt_id integer,

    held_amount numeric(12,2) NOT NULL,
    fee_amount numeric(12,2) DEFAULT 0.00 NOT NULL,
    seller_receive numeric(12,2) NOT NULL,

    status character varying(20)
        DEFAULT 'AwaitingPayment' NOT NULL,

    created_at timestamp with time zone
        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    held_at timestamp with time zone,
    released_at timestamp with time zone,
    refunded_at timestamp with time zone,
    updated_at timestamp with time zone
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT deal_escrow_pkey
        PRIMARY KEY (room_id),

    CONSTRAINT deal_escrow_room_code_unique
        UNIQUE (room_code),

    CONSTRAINT deal_escrow_room_fkey
        FOREIGN KEY (room_id)
        REFERENCES public.room(room_id)
        ON DELETE RESTRICT,

    CONSTRAINT deal_escrow_buyer_fkey
        FOREIGN KEY (buyer_id)
        REFERENCES public.user_login(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT deal_escrow_seller_fkey
        FOREIGN KEY (seller_id)
        REFERENCES public.user_login(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT deal_escrow_payment_attempt_fkey
        FOREIGN KEY (payment_attempt_id)
        REFERENCES public.deal_payment_attempt(
            payment_attempt_id
        )
        ON DELETE SET NULL,

    CONSTRAINT deal_escrow_payment_method_check
        CHECK (
            payment_method IN ('Wallet', 'KHQR')
        ),

    CONSTRAINT deal_escrow_status_check
        CHECK (
            status IN (
                'AwaitingPayment',
                'Held',
                'Disputed',
                'Released',
                'Refunded'
            )
        ),

    CONSTRAINT deal_escrow_amounts_check
        CHECK (
            held_amount > 0
            AND fee_amount >= 0
            AND seller_receive >= 0
            AND seller_receive <= held_amount
        )
);


-- Permanent history of every wallet balance movement.
CREATE TABLE IF NOT EXISTS public.wallet_transactions (
    wallet_transaction_id integer
        GENERATED BY DEFAULT AS IDENTITY,

    user_id integer NOT NULL,

    -- room_id can become NULL after temporary room cleanup.
    room_id integer,
    room_code character varying(10),

    payment_attempt_id integer,

    transaction_type character varying(30) NOT NULL,
    amount numeric(12,2) NOT NULL,

    available_change numeric(12,2)
        DEFAULT 0.00 NOT NULL,
    pending_change numeric(12,2)
        DEFAULT 0.00 NOT NULL,

    available_balance_after numeric(12,2) NOT NULL,
    pending_balance_after numeric(12,2) NOT NULL,

    -- Example: deal:QY9UZR:wallet_hold
    reference_key character varying(150) NOT NULL,

    description text,
    created_at timestamp with time zone
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT wallet_transactions_pkey
        PRIMARY KEY (wallet_transaction_id),

    CONSTRAINT wallet_transactions_reference_unique
        UNIQUE (reference_key),

    CONSTRAINT wallet_transactions_user_fkey
        FOREIGN KEY (user_id)
        REFERENCES public.user_login(user_id)
        ON DELETE RESTRICT,

    CONSTRAINT wallet_transactions_room_fkey
        FOREIGN KEY (room_id)
        REFERENCES public.room(room_id)
        ON DELETE SET NULL,

    CONSTRAINT wallet_transactions_payment_attempt_fkey
        FOREIGN KEY (payment_attempt_id)
        REFERENCES public.deal_payment_attempt(
            payment_attempt_id
        )
        ON DELETE SET NULL,

    CONSTRAINT wallet_transactions_type_check
        CHECK (
            transaction_type IN (
                'Deposit',
                'DealHold',
                'EscrowRelease',
                'Refund',
                'SellerCredit',
                'Withdrawal',
                'Fee'
            )
        ),

    CONSTRAINT wallet_transactions_amount_positive
        CHECK (amount > 0),

    CONSTRAINT wallet_transactions_changes_check
        CHECK (
            available_change <> 0
            OR pending_change <> 0
        ),

    CONSTRAINT wallet_transactions_balances_nonnegative
        CHECK (
            available_balance_after >= 0
            AND pending_balance_after >= 0
        )
);

-- Upgrade databases where wallet_transactions was
-- previously created with room_code as NOT NULL.
ALTER TABLE public.wallet_transactions
    ALTER COLUMN room_code DROP NOT NULL;
CREATE INDEX IF NOT EXISTS
    deal_escrow_buyer_status_idx
ON public.deal_escrow (
    buyer_id,
    status
);
CREATE INDEX IF NOT EXISTS
    deal_escrow_seller_status_idx
ON public.deal_escrow (
    seller_id,
    status
);
CREATE INDEX IF NOT EXISTS
    wallet_transactions_user_created_idx
ON public.wallet_transactions (
    user_id,
    created_at DESC
);
CREATE INDEX IF NOT EXISTS
    wallet_transactions_room_code_idx
ON public.wallet_transactions (
    room_code,
    created_at DESC
);

-- Permanent service-fee ledger for both completed and
-- cancelled funded deals.
CREATE TABLE IF NOT EXISTS
    public.platform_fee_transactions (
        platform_fee_transaction_id integer
            GENERATED BY DEFAULT AS IDENTITY,

        room_id integer,
        room_code character varying(10) NOT NULL,
        -- Present only for completed deals.
        transaction_id integer,
        -- User economically charged for the fee.
        charged_user_id integer NOT NULL,
        -- The payer selected during fee negotiation.
        agreed_fee_payer character varying(6) NOT NULL,
        event_type character varying(20) NOT NULL,
        payment_method character varying(20) NOT NULL,
        fee_amount numeric(12,2) NOT NULL,
        currency character varying(3)
            DEFAULT 'USD' NOT NULL,
        reference_key character varying(150) NOT NULL,
        created_at timestamp with time zone
            DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT platform_fee_transactions_pkey
            PRIMARY KEY (
                platform_fee_transaction_id
            ),
        CONSTRAINT platform_fee_reference_unique
            UNIQUE (reference_key),
        CONSTRAINT platform_fee_room_fkey
            FOREIGN KEY (room_id)
            REFERENCES public.room(room_id)
            ON DELETE SET NULL,

        CONSTRAINT platform_fee_history_fkey
            FOREIGN KEY (transaction_id)
            REFERENCES public.transactions_history(
                transaction_id
            )
            ON DELETE SET NULL,

        CONSTRAINT platform_fee_user_fkey
            FOREIGN KEY (charged_user_id)
            REFERENCES public.user_login(user_id)
            ON DELETE RESTRICT,

        CONSTRAINT platform_fee_payer_check
            CHECK (
                agreed_fee_payer IN (
                    'buyer',
                    'seller'
                )
            ),

        CONSTRAINT platform_fee_event_check
            CHECK (
                event_type IN (
                    'Completed',
                    'Cancelled'
                )
            ),

        CONSTRAINT platform_fee_method_check
            CHECK (
                payment_method IN (
                    'Wallet',
                    'KHQR'
                )
            ),

        CONSTRAINT platform_fee_amount_positive
            CHECK (fee_amount > 0),

        CONSTRAINT platform_fee_currency_check
            CHECK (currency = 'USD')
            );


-- This project supports USD only.
ALTER TABLE public.deal_payment_attempt
    DROP CONSTRAINT IF EXISTS
        deal_payment_attempt_currency_check;




ALTER TABLE public.deal_payment_attempt
    ADD CONSTRAINT
        deal_payment_attempt_currency_check
    CHECK (currency = 'USD');




-- Temporary mutual-cancellation agreement for a funded deal.
CREATE TABLE IF NOT EXISTS
    public.deal_cancellation_request (
        room_id integer NOT NULL,
        requested_by integer NOT NULL,
        rejected_by integer,

        reason text NOT NULL,

        buyer_confirmed boolean
            DEFAULT false NOT NULL,
        seller_confirmed boolean
            DEFAULT false NOT NULL,

        status character varying(20)
            DEFAULT 'Pending' NOT NULL,

        refund_amount numeric(12,2),
        retained_fee numeric(12,2),

        requested_at timestamp with time zone
            DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_at timestamp with time zone
            DEFAULT CURRENT_TIMESTAMP NOT NULL,
        processed_at timestamp with time zone,

        CONSTRAINT deal_cancellation_request_pkey
            PRIMARY KEY (room_id),

        CONSTRAINT deal_cancellation_room_fkey
            FOREIGN KEY (room_id)
            REFERENCES public.room(room_id)
            ON DELETE CASCADE,

        CONSTRAINT deal_cancellation_requester_fkey
            FOREIGN KEY (requested_by)
            REFERENCES public.user_login(user_id)
            ON DELETE RESTRICT,

        CONSTRAINT deal_cancellation_rejected_by_fkey
            FOREIGN KEY (rejected_by)
            REFERENCES public.user_login(user_id)
            ON DELETE RESTRICT,

        CONSTRAINT deal_cancellation_status_check
            CHECK (
                status IN (
                    'Pending',
                    'Rejected',
                    'Processed'
                )
            ),

        CONSTRAINT deal_cancellation_reason_check
            CHECK (
                length(trim(reason)) >= 5
            ),

        CONSTRAINT deal_cancellation_amounts_check
            CHECK (
                (
                    refund_amount IS NULL
                    OR refund_amount >= 0
                )
                AND (
                    retained_fee IS NULL
                    OR retained_fee >= 0
                )
            )
    );
-- Indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_details_username ON public.user_details USING btree (username);
CREATE INDEX IF NOT EXISTS idx_room_reminders_cooldown ON public.room_reminders USING btree (room_id, sender_id, created_at DESC);
CREATE INDEX IF NOT EXISTS
    room_messages_room_message_idx
ON public.room_messages (
    room_id,
    message_id
);
CREATE INDEX IF NOT EXISTS idx_room_reminders_unread ON public.room_reminders USING btree (receiver_id, is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS
    deal_payment_attempt_room_created_idx
ON public.deal_payment_attempt (
    room_id,
    created_at DESC
);

CREATE INDEX IF NOT EXISTS
    deal_payment_attempt_status_expires_idx
ON public.deal_payment_attempt (
    status,
    expires_at
);

CREATE INDEX IF NOT EXISTS
    deal_cancellation_status_updated_idx
ON public.deal_cancellation_request (
    status,
    updated_at DESC
);
-- A room may create only one permanent completed
-- transaction-history record.
CREATE UNIQUE INDEX IF NOT EXISTS
    transactions_history_room_code_unique
ON public.transactions_history (room_code)
WHERE room_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS
    platform_fee_room_code_idx
ON public.platform_fee_transactions (
    room_code,
    created_at DESC
);

CREATE INDEX IF NOT EXISTS
    platform_fee_event_created_idx
ON public.platform_fee_transactions (
    event_type,
    created_at DESC
);
-- Backfill platform fees from completed deals that
-- existed before platform_fee_transactions was added.
INSERT INTO public.platform_fee_transactions (
    room_id,
    room_code,
    transaction_id,
    charged_user_id,
    agreed_fee_payer,
    event_type,
    payment_method,
    fee_amount,
    currency,
    reference_key
)
SELECT
    th.room_id,
    th.room_code,
    th.transaction_id,
    CASE
        WHEN th.fee_payer = 'seller'
            THEN th.seller_id
        ELSE th.buyer_id
    END,
    COALESCE(
        th.fee_payer,
        'buyer'
    ),
    'Completed',
    CASE
        WHEN th.payment_provider = 'Wallet'
            THEN 'Wallet'
        ELSE 'KHQR'
    END,
    th.fee_amount,
    'USD',
    (
        'deal:'
        || th.room_code
        || ':completed_fee'
    )
FROM public.transactions_history th
WHERE th.transaction_status = 'Completed'
  AND th.room_code IS NOT NULL
  AND th.fee_amount > 0
ON CONFLICT (reference_key) DO NOTHING;
-- Persistent notifications belonging to individual users.
CREATE TABLE IF NOT EXISTS public.user_notifications (
    notification_id bigint
        GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    actor_user_id integer,
    notification_type character varying(40)
        NOT NULL,
    title character varying(255) NOT NULL,
    message text NOT NULL,
    room_id integer,
    room_code character varying(20),
    announcement_id integer,
    is_read boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT user_notifications_pkey
        PRIMARY KEY (notification_id),

    CONSTRAINT user_notifications_user_fkey
        FOREIGN KEY (user_id)
        REFERENCES public.user_login(user_id)
        ON DELETE CASCADE,

    CONSTRAINT user_notifications_actor_fkey
        FOREIGN KEY (actor_user_id)
        REFERENCES public.user_login(user_id)
        ON DELETE SET NULL,

    CONSTRAINT user_notifications_room_fkey
        FOREIGN KEY (room_id)
        REFERENCES public.room(room_id)
        ON DELETE SET NULL,

    CONSTRAINT user_notifications_announcement_fkey
        FOREIGN KEY (announcement_id)
        REFERENCES public.announcements(
            announcement_id
        )
        ON DELETE CASCADE,

    CONSTRAINT user_notifications_type_check
        CHECK (
            notification_type::text = ANY (
                ARRAY[
                    'Announcement',
                    'DealReminder',
                    'InvitationAccepted',
                    'InvitationRejected',
                    'CancellationRequested',
                    'CancellationRejected',
                    'DealCancelled'
                ]::text[]
            )
        ),

    CONSTRAINT user_notifications_title_not_blank
        CHECK (length(trim(title)) > 0),

    CONSTRAINT user_notifications_message_not_blank
        CHECK (length(trim(message)) > 0)
);

-- Expand persistent notification types for room and
-- cancellation workflow events.
ALTER TABLE public.user_notifications
DROP CONSTRAINT IF EXISTS
    user_notifications_type_check;

ALTER TABLE public.user_notifications
ADD CONSTRAINT user_notifications_type_check
CHECK (
    notification_type::text = ANY (
        ARRAY[
            'Announcement',
            'DealReminder',
            'InvitationAccepted',
            'InvitationRejected',
            'CancellationRequested',
            'CancellationRejected',
            'DealCancelled'
        ]::text[]
    )
);

CREATE INDEX IF NOT EXISTS
    user_notifications_user_created_idx
ON public.user_notifications (
    user_id,
    created_at DESC,
    notification_id DESC
);

CREATE INDEX IF NOT EXISTS
    user_notifications_user_unread_idx
ON public.user_notifications (
    user_id,
    is_read,
    created_at DESC
);

CREATE UNIQUE INDEX IF NOT EXISTS
    user_notifications_announcement_user_unique
ON public.user_notifications (
    announcement_id,
    user_id
)
WHERE announcement_id IS NOT NULL;

-- Give existing users a personal copy of every active
-- announcement created before this table existed.
INSERT INTO public.user_notifications (
    user_id,
    notification_type,
    title,
    message,
    announcement_id,
    is_read,
    created_at
)
SELECT
    login.user_id,
    'Announcement',
    announcement.title,
    announcement.message,
    announcement.announcement_id,
    false,
    announcement.created_at
FROM public.user_login login
CROSS JOIN public.announcements announcement
WHERE announcement.is_active = true
ON CONFLICT (
    announcement_id,
    user_id
)
WHERE announcement_id IS NOT NULL
DO NOTHING;

-- Move sequences beyond current IDs so future inserts do not collide.
SELECT setval('public.user_login_user_id_seq', GREATEST(COALESCE((SELECT MAX(user_id) FROM public.user_login), 0), 1), EXISTS (SELECT 1 FROM public.user_login));
SELECT setval('public.admin_login_admin_id_seq', GREATEST(COALESCE((SELECT MAX(admin_id) FROM public.admin_login), 0), 1), EXISTS (SELECT 1 FROM public.admin_login));
SELECT setval('public.user_wallet_wallet_id_seq', GREATEST(COALESCE((SELECT MAX(wallet_id) FROM public.user_wallet), 0), 1), EXISTS (SELECT 1 FROM public.user_wallet));
SELECT setval('public.room_room_id_seq', GREATEST(COALESCE((SELECT MAX(room_id) FROM public.room), 0), 1), EXISTS (SELECT 1 FROM public.room));
SELECT setval('public.room_messages_message_id_seq', GREATEST(COALESCE((SELECT MAX(message_id) FROM public.room_messages), 0), 1), EXISTS (SELECT 1 FROM public.room_messages));
SELECT setval('public.transactions_history_transaction_id_seq', GREATEST(COALESCE((SELECT MAX(transaction_id) FROM public.transactions_history), 0), 1), EXISTS (SELECT 1 FROM public.transactions_history));
SELECT setval('public.deal_proofs_proof_id_seq', GREATEST(COALESCE((SELECT MAX(proof_id) FROM public.deal_proofs), 0), 1), EXISTS (SELECT 1 FROM public.deal_proofs));
SELECT setval('public.disputes_dispute_id_seq', GREATEST(COALESCE((SELECT MAX(dispute_id) FROM public.disputes), 0), 1), EXISTS (SELECT 1 FROM public.disputes));
SELECT setval('public.dispute_resolution_resolution_id_seq', GREATEST(COALESCE((SELECT MAX(resolution_id) FROM public.dispute_resolution), 0), 1), EXISTS (SELECT 1 FROM public.dispute_resolution));
SELECT setval('public.faq_questions_question_id_seq', GREATEST(COALESCE((SELECT MAX(question_id) FROM public.faq_questions), 0), 1), EXISTS (SELECT 1 FROM public.faq_questions));
SELECT setval('public.room_reminders_reminder_id_seq', GREATEST(COALESCE((SELECT MAX(reminder_id) FROM public.room_reminders), 0), 1), EXISTS (SELECT 1 FROM public.room_reminders));
COMMIT;